In [13]:
people = {'first' : ['rifat', 'anik', 'samsu', 'khal'], 'last' : ['khan', 'hal', 'pop','pop'], 'age': [20, 22, 32,35]}

In [14]:
import pandas as pd

In [15]:
df = pd.DataFrame(people)

In [16]:
df

   first  last  age
0  rifat  khan   20
1   anik   hal   22
2  samsu   pop   32
3   khal   pop   35

In [18]:
df.sort_values(by=['last', 'first'],ascending= [False, True])

   first  last  age
3   khal   pop   35
2  samsu   pop   32
0  rifat  khan   20
1   anik   hal   22

In [7]:
df.sort_index()

   first  last  age
0  rifat  khan   20
1   anik   hal   22
2  samsu   pop   32

In [19]:
df['last'].sort_values()

1     hal
0    khan
2     pop
3     pop
Name: last, dtype: object

In [22]:
df = pd.read_csv('data/survey_results_public.csv')

In [23]:
df

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88878,88377,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,...,NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88879,88601,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88880,88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88881,88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88882,88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",...,Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

In [42]:
df.sort_values(by ='Country', ascending = False)

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
60693,61083,I am a student who is learning to code,Yes,Never,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",Zimbabwe,"Yes, part-time",Some college/university study without earning ...,"Computer science, computer engineering, or sof...",...,A lot less welcome now than last year,Tech articles written by other developers;Indu...,26.0,Man,NaN,NaN,Black or of African descent,Yes,Too long,Neither easy nor difficult
47789,48100,I code primarily as a hobby,Yes,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",Zimbabwe,No,"Secondary school (e.g. American high school, G...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,26.0,Man,No,Straight / Heterosexual,Black or of African descent,No,Appropriate in length,Easy
6466,6492,I am a developer by profession,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Zimbabwe,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,29.0,Man,No,Straight / Heterosexual,Black or of African descent,Yes,Appropriate in length,Easy
66038,66459,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Zimbabwe,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Courses on technologies you're interested in,29.0,Man,No,Straight / Heterosexual,Black or of African descent,Yes,Too long,Difficult
6460,6486,I am a student who is learning to code,Yes,Never,"OSS is, on average, of HIGHER quality than pro...",Employed part-time,Zimbabwe,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,A lot more welcome now than last year,Tech articles written by other developers;Indu...,21.0,Woman,No,Straight / Heterosexual,Black or of African descent,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88873,88062,NaN,No,Never,"OSS is, on average, of LOWER quality than prop...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88874,88076,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88879,88601,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88880,88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88881,88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
df[['Country','Age','ConvertedComp']].head(50)

           Country   Age  ConvertedComp
39018  Afghanistan  26.0        19152.0
86551  Afghanistan   NaN            NaN
58390  Afghanistan   NaN            NaN
73920  Afghanistan  23.0            NaN
28877  Afghanistan   NaN            NaN
51525  Afghanistan   NaN            NaN
45562  Afghanistan  85.0            NaN
46807  Afghanistan  21.0            NaN
44123  Afghanistan  25.0            NaN
22327  Afghanistan  24.0         7980.0
8112   Afghanistan  24.0         1596.0
80423  Afghanistan  18.0            NaN
59184  Afghanistan   NaN            NaN
60185  Afghanistan  23.0            NaN
37571  Afghanistan   NaN            NaN
29560  Afghanistan  26.0         1116.0
42832  Afghanistan   NaN            NaN
12253  Afghanistan   NaN            NaN
58082  Afghanistan  26.0        17556.0
50172  Afghanistan  34.0       153216.0
7323   Afghanistan   NaN            NaN
7056   Afghanistan  26.0        14364.0
61770  Afghanistan   NaN            NaN
86394  Afghanistan  25.0            NaN
85293  Afghanistan  24.0            NaN
85185  Afghanistan  28.0            NaN
50437  Afghanistan   NaN            NaN
88340  Afghanistan  60.0            NaN
88735  Afghanistan   NaN            NaN
6391   Afghanistan   NaN            NaN
39754  Afghanistan   NaN            NaN
88181  Afghanistan   NaN            NaN
48122  Afghanistan  24.0         4464.0
62723  Afghanistan   NaN      1000000.0
62124  Afghanistan  18.0            NaN
49377  Afghanistan   NaN            NaN
32971  Afghanistan   NaN            NaN
60559  Afghanistan  25.0            NaN
85827  Afghanistan   NaN            NaN
88033  Afghanistan  32.0            NaN
28470  Afghanistan   NaN            0.0
719    Afghanistan   1.0            0.0
26189  Afghanistan   NaN            NaN
10697  Afghanistan  24.0         3996.0
58394      Albania  23.0         7176.0
43601      Albania  29.0        20628.0
73036      Albania  20.0         7728.0
11496      Albania  22.0         6624.0
64380      Albania  35.0        33120.0
65859      Albania  27.0        41244.0

In [46]:
df.sort_values(by = ['Country','ConvertedComp'],ascending=[True, False], inplace = True)

In [47]:
df[['Country','ConvertedComp']]

           Country  ConvertedComp
62723  Afghanistan      1000000.0
50172  Afghanistan       153216.0
39018  Afghanistan        19152.0
58082  Afghanistan        17556.0
7056   Afghanistan        14364.0
...            ...            ...
88873          NaN            NaN
88874          NaN            NaN
88879          NaN            NaN
88880          NaN            NaN
88881          NaN            NaN

[88883 rows x 2 columns]

In [48]:
df['ConvertedComp'].nlargest(20)

25833    2000000.0
87353    2000000.0
28080    2000000.0
72274    2000000.0
21895    2000000.0
77665    2000000.0
79701    2000000.0
51798    2000000.0
75088    2000000.0
32056    2000000.0
83866    2000000.0
50196    2000000.0
50200    2000000.0
58134    2000000.0
58147    2000000.0
58118    2000000.0
58307    2000000.0
49819    2000000.0
59892    2000000.0
47557    2000000.0
Name: ConvertedComp, dtype: float64

In [49]:
df.nlargest(10, 'ConvertedComp')

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
25833,25983,I am a developer by profession,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Canada,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,NaN,24.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
87353,87896,I am a developer by profession,Yes,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,Germany,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,32.0,Man,No,Gay or Lesbian,White or of European descent,No,Appropriate in length,Neither easy nor difficult
28080,28243,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",...,A lot less welcome now than last year,Tech meetups or events in your area,NaN,NaN,NaN,Straight / Heterosexual,NaN,Yes,Too short,Easy
72274,72732,"I am not primarily a developer, but I write co...",No,Less than once a month but more than once per ...,"OSS is, on average, of LOWER quality than prop...",NaN,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,A lot less welcome now than last year,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,Yes,Too long,Easy
21895,22013,I am a developer by profession,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,India,No,"Professional degree (JD, MD, etc.)","A natural science (ex. biology, chemistry, phy...",...,A lot more welcome now than last year,Tech articles written by other developers;Indu...,NaN,Man,No,Straight / Heterosexual,NaN,Yes,Too long,Easy
77665,78151,I am a developer by profession,Yes,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Mexico,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,32.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina,No,Appropriate in length,Easy
79701,80200,I am a developer by profession,Yes,Never,"OSS is, on average, of LOWER quality than prop...",Employed full-time,Netherlands,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,NaN,Tech articles written by other developers,25.0,Woman,No,Bisexual,White or of European descent,No,Appropriate in length,Easy
51798,52132,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Peru,No,Some college/university study without earning ...,I never declared a major,...,Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,48.0,Man,NaN,NaN,Black or of African descent;East Asian;Hispani...,Yes,Appropriate in length,Easy
75088,75561,I am a developer by profession,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,Employed full-time,Singapore,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","A humanities discipline (ex. literature, histo...",...,Just as welcome now as I felt last year,Tech meetups or events in your area,37.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
32056,32250,I am a developer by profession,Yes,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,Switzerland,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Industry news about technologies you're intere...,30.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy